// 全テーブルの公開エクスポート。drizzle-kit はこのファイルから schema を辿る。
export * from "./schools.js";
export * from "./users.js";
export * from "./classes.js";
export * from "./memberships.js";
export * from "./magic-links.js";
export * from "./contents.js";
export * from "./content-versions.js";
export * from "./publishes.js";
export * from "./events.js";
export * from "./ai-extractions.js";
export * from "./ai-chat-sessions.js";
export * from "./ai-chat-messages.js";
export * from "./advertisers.js";
export * from "./contracts.js";
export * from "./communications.js";
export * from "./monthly-reports.js";
export * from "./system-admins.js";
export * from "./audit-log.js";
